# -*- coding: utf-8 -*-
"""notes_summarizer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Imn8LiLy1aodfjan-lkqa6q44otG4wtH
"""

pip install pillow pytesseract sentence-transformers transformers==4.30.2 scikit-learn --force-reinstall

!apt-get install tesseract-ocr

!pip install --upgrade pip
!pip install pillow pytesseract sentence-transformers transformers==4.30.2 scikit-learn --force-reinstall

from PIL import Image
import pytesseract
from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity

# Configure pytesseract to find the Tesseract executable in Colab environment
pytesseract.pytesseract.tesseract_cmd = '/usr/bin/tesseract'

# Load Image
image_path = "/content/sample.jpeg"

# NOTE: You need to upload a 'sample.png' file to your Colab environment for this to work.
# For example, you can drag and drop a file into the files section on the left sidebar.

img = Image.open(image_path)

# Extract text from image
text = pytesseract.image_to_string(img)

print("\nExtracted Text:\n")
print(text)

# Split into chunks
chunks = text.split('.')
chunks = [chunk.strip() for chunk in chunks if chunk.strip()]

# Embedding model
model = SentenceTransformer('sentence-transformers/all-MiniLM-L6-v2')

# Create embeddings
embeddings = model.encode(chunks)

# User Query
query = input("\nAsk a question: ")

query_embedding = model.encode(query)

# Similarity Search
similarities = cosine_similarity(
    [query_embedding],
    embeddings
)

best_match_index = similarities.argmax()

print("\nAnswer:")
print(chunks[best_match_index])



import numpy as np

top_k = 3

indices = np.argsort(similarities[0])[::-1][:top_k]

context = "\n".join([chunks[i] for i in indices])

print("\nRelevant Information:")
print(context)

from google import genai
from PIL import Image

client = genai.Client(api_key="YOUR_API_KEY")

image = Image.open("sample.png")

response = client.models.generate_content(
    model="gemini-2.5-flash",
    contents=[
        image,
        "Answer questions from this image"
    ]
)

print(response.text)

from langchain_community.document_loaders import ImageCaptionLoader

from unstructured.partition.image import partition_image

